config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get 'home/index' 
  resources :arquives
  resources :classes
  resources :administrators
  resources :professors
  resources :students
  resources :courses
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/classes_controller.rb
class ClassesController < ApplicationController
  before_action :set_class, only: [:show, :edit, :update, :destroy]

  # GET /classes
  # GET /classes.json
  def index
    @classes = Classe.all
  end

  # GET /classes/1
  # GET /classes/1.json
  def show
  end

  # GET /classes/new
  def new
    @class = Classe.new
  end

  # GET /classes/1/edit
  def edit
  end

  # POST /classes
  # POST /classes.json
  def create
    @class = Classe.new(class_params)

    respond_to do |format|
      if @class.save
        format.html { redirect_to @class, notice: 'Classe was successfully created.' }
        format.json { render :show, status: :created, location: @class }
      else
        format.html { render :new }
        format.json { render json: @class.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /classes/1
  # PATCH/PUT /classes/1.json
  def update
    respond_to do |format|
      if @class.update(class_params)
        format.html { redirect_to @class, notice: 'Classe was successfully updated.' }
        format.json { render :show, status: :ok, location: @class }
      else
        format.html { render :edit }
        format.json { render json: @class.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /classes/1
  # DELETE /classes/1.json
  def destroy
    @class.destroy
    respond_to do |format|
      format.html { redirect_to classes_url, notice: 'Classe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_class
      @class = Classe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def class_params
      params.require(:class).permit(:course_id, :professor_id)
    end
end

app/helpers/classes_helper.rb
module ClassesHelper
end

app/views/classes/_form.html.erb
<%= form_with(model: class, local: true) do |form| %>
  <% if class.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(class.errors.count, "error") %> prohibited this class from being saved:</h2>

      <ul>
      <% class.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :course_id %>
    <%= form.text_field :course_id %>
  </div>

  <div class="field">
    <%= form.label :professor_id %>
    <%= form.text_field :professor_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/classes/edit.html.erb
<h1>Editing Class</h1>

<%= render 'form', class: @class %>

<%= link_to 'Show', @class %> |
<%= link_to 'Back', classes_path %>

app/views/classes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Classes</h1>

<table>
  <thead>
    <tr>
      <th>Course</th>
      <th>Professor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @classes.each do |class| %>
      <tr>
        <td><%= class.course %></td>
        <td><%= class.professor %></td>
        <td><%= link_to 'Show', class %></td>
        <td><%= link_to 'Edit', edit_class_path(class) %></td>
        <td><%= link_to 'Destroy', class, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Class', new_class_path %>

app/views/classes/new.html.erb
<h1>New Class</h1>

<%= render 'form', class: @class %>

<%= link_to 'Back', classes_path %>

app/views/classes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Course:</strong>
  <%= @class.course %>
</p>

<p>
  <strong>Professor:</strong>
  <%= @class.professor %>
</p>

<%= link_to 'Edit', edit_class_path(@class) %> |
<%= link_to 'Back', classes_path %>